/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.style.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.graphview.style.ui.internal.StyleActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GraphViewStyleUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StyleActivator.getInstance().getInjector("org.eclipse.xtext.graphview.style.GraphViewStyle");
	}

}
