/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.style.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractGraphViewStyleScopeProvider extends XbaseBatchScopeProvider {
}
