/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.map.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.graphview.map.ui.internal.MapActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GraphViewMappingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MapActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MapActivator activator = MapActivator.getInstance();
		return activator != null ? activator.getInjector(MapActivator.ORG_ECLIPSE_XTEXT_GRAPHVIEW_MAP_GRAPHVIEWMAPPING) : null;
	}

}
