/**
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.style.scoping;

import org.eclipse.xtext.graphview.style.scoping.AbstractGraphViewStyleScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GraphViewStyleScopeProvider extends AbstractGraphViewStyleScopeProvider {
}
