/**
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.style;

import org.eclipse.xtext.graphview.style.GraphViewStyleStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GraphViewStyleStandaloneSetup extends GraphViewStyleStandaloneSetupGenerated {
  public static void doSetup() {
    new GraphViewStyleStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
