/**
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.style;

import org.eclipse.xtext.graphview.style.AbstractGraphViewStyleRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GraphViewStyleRuntimeModule extends AbstractGraphViewStyleRuntimeModule {
}
