/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.map.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.xbase.services.XbaseGrammarAccess;
import org.eclipse.xtext.xbase.services.XtypeGrammarAccess;

@Singleton
public class GraphViewMappingGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class DiagramMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.xtext.graphview.map.GraphViewMapping.DiagramMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cImportSectionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cImportSectionXImportSectionParserRuleCall_0_0 = (RuleCall)cImportSectionAssignment_0.eContents().get(0);
		private final Keyword cDiagramKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameQualifiedNameParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeGuardAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeGuardJvmTypeReferenceParserRuleCall_4_0 = (RuleCall)cTypeGuardAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cMappingsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cMappingsAbstractExpressionMappingParserRuleCall_6_0 = (RuleCall)cMappingsAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cUnlessKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cUnlessConditionAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cUnlessConditionXExpressionParserRuleCall_8_1_0 = (RuleCall)cUnlessConditionAssignment_8_1.eContents().get(0);
		
		//DiagramMapping:
		//	importSection=XImportSection?
		//	'diagram' name=QualifiedName 'type' typeGuard=JvmTypeReference '{'
		//	mappings+=AbstractExpressionMapping*
		//	'}' ('unless' unlessCondition=XExpression)?;
		@Override public ParserRule getRule() { return rule; }
		
		//importSection=XImportSection? 'diagram' name=QualifiedName 'type' typeGuard=JvmTypeReference '{'
		//mappings+=AbstractExpressionMapping* '}' ('unless' unlessCondition=XExpression)?
		public Group getGroup() { return cGroup; }
		
		//importSection=XImportSection?
		public Assignment getImportSectionAssignment_0() { return cImportSectionAssignment_0; }
		
		//XImportSection
		public RuleCall getImportSectionXImportSectionParserRuleCall_0_0() { return cImportSectionXImportSectionParserRuleCall_0_0; }
		
		//'diagram'
		public Keyword getDiagramKeyword_1() { return cDiagramKeyword_1; }
		
		//name=QualifiedName
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_2_0() { return cNameQualifiedNameParserRuleCall_2_0; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//typeGuard=JvmTypeReference
		public Assignment getTypeGuardAssignment_4() { return cTypeGuardAssignment_4; }
		
		//JvmTypeReference
		public RuleCall getTypeGuardJvmTypeReferenceParserRuleCall_4_0() { return cTypeGuardJvmTypeReferenceParserRuleCall_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//mappings+=AbstractExpressionMapping*
		public Assignment getMappingsAssignment_6() { return cMappingsAssignment_6; }
		
		//AbstractExpressionMapping
		public RuleCall getMappingsAbstractExpressionMappingParserRuleCall_6_0() { return cMappingsAbstractExpressionMappingParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
		
		//('unless' unlessCondition=XExpression)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'unless'
		public Keyword getUnlessKeyword_8_0() { return cUnlessKeyword_8_0; }
		
		//unlessCondition=XExpression
		public Assignment getUnlessConditionAssignment_8_1() { return cUnlessConditionAssignment_8_1; }
		
		//XExpression
		public RuleCall getUnlessConditionXExpressionParserRuleCall_8_1_0() { return cUnlessConditionXExpressionParserRuleCall_8_1_0; }
	}
	public class AbstractExpressionMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.xtext.graphview.map.GraphViewMapping.AbstractExpressionMapping");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNodeMappingParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLabelMappingParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cEdgeMappingParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMappingCallParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//AbstractExpressionMapping:
		//	NodeMapping | LabelMapping | EdgeMapping | MappingCall;
		@Override public ParserRule getRule() { return rule; }
		
		//NodeMapping | LabelMapping | EdgeMapping | MappingCall
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NodeMapping
		public RuleCall getNodeMappingParserRuleCall_0() { return cNodeMappingParserRuleCall_0; }
		
		//LabelMapping
		public RuleCall getLabelMappingParserRuleCall_1() { return cLabelMappingParserRuleCall_1; }
		
		//EdgeMapping
		public RuleCall getEdgeMappingParserRuleCall_2() { return cEdgeMappingParserRuleCall_2; }
		
		//MappingCall
		public RuleCall getMappingCallParserRuleCall_3() { return cMappingCallParserRuleCall_3; }
	}
	public class NodeMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.xtext.graphview.map.GraphViewMapping.NodeMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cHiddenAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cHiddenHiddenKeyword_0_0 = (Keyword)cHiddenAssignment_0.eContents().get(0);
		private final Keyword cNodeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cForKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMultiAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cMultiEachKeyword_4_0 = (Keyword)cMultiAssignment_4.eContents().get(0);
		private final Assignment cExpressionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cExpressionXExpressionParserRuleCall_5_0 = (RuleCall)cExpressionAssignment_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cMappingsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cMappingsAbstractExpressionMappingParserRuleCall_7_0 = (RuleCall)cMappingsAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cUnlessKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cUnlessConditionAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cUnlessConditionXExpressionParserRuleCall_9_1_0 = (RuleCall)cUnlessConditionAssignment_9_1.eContents().get(0);
		
		//NodeMapping:
		//	^hidden?='hidden'? 'node' name=ID 'for' multi?='each'? expression=XExpression '{'
		//	mappings+=AbstractExpressionMapping*
		//	'}' ('unless' unlessCondition=XExpression)?;
		@Override public ParserRule getRule() { return rule; }
		
		//^hidden?='hidden'? 'node' name=ID 'for' multi?='each'? expression=XExpression '{' mappings+=AbstractExpressionMapping*
		//'}' ('unless' unlessCondition=XExpression)?
		public Group getGroup() { return cGroup; }
		
		//^hidden?='hidden'?
		public Assignment getHiddenAssignment_0() { return cHiddenAssignment_0; }
		
		//'hidden'
		public Keyword getHiddenHiddenKeyword_0_0() { return cHiddenHiddenKeyword_0_0; }
		
		//'node'
		public Keyword getNodeKeyword_1() { return cNodeKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'for'
		public Keyword getForKeyword_3() { return cForKeyword_3; }
		
		//multi?='each'?
		public Assignment getMultiAssignment_4() { return cMultiAssignment_4; }
		
		//'each'
		public Keyword getMultiEachKeyword_4_0() { return cMultiEachKeyword_4_0; }
		
		//expression=XExpression
		public Assignment getExpressionAssignment_5() { return cExpressionAssignment_5; }
		
		//XExpression
		public RuleCall getExpressionXExpressionParserRuleCall_5_0() { return cExpressionXExpressionParserRuleCall_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//mappings+=AbstractExpressionMapping*
		public Assignment getMappingsAssignment_7() { return cMappingsAssignment_7; }
		
		//AbstractExpressionMapping
		public RuleCall getMappingsAbstractExpressionMappingParserRuleCall_7_0() { return cMappingsAbstractExpressionMappingParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//('unless' unlessCondition=XExpression)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'unless'
		public Keyword getUnlessKeyword_9_0() { return cUnlessKeyword_9_0; }
		
		//unlessCondition=XExpression
		public Assignment getUnlessConditionAssignment_9_1() { return cUnlessConditionAssignment_9_1; }
		
		//XExpression
		public RuleCall getUnlessConditionXExpressionParserRuleCall_9_1_0() { return cUnlessConditionXExpressionParserRuleCall_9_1_0; }
	}
	public class LabelMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.xtext.graphview.map.GraphViewMapping.LabelMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cHiddenAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cHiddenHiddenKeyword_0_0 = (Keyword)cHiddenAssignment_0.eContents().get(0);
		private final Keyword cLabelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cForKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMultiAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cMultiEachKeyword_4_0 = (Keyword)cMultiAssignment_4.eContents().get(0);
		private final Assignment cExpressionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cExpressionXExpressionParserRuleCall_5_0 = (RuleCall)cExpressionAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cUnlessKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cUnlessConditionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cUnlessConditionXExpressionParserRuleCall_6_1_0 = (RuleCall)cUnlessConditionAssignment_6_1.eContents().get(0);
		
		//LabelMapping:
		//	^hidden?='hidden'? 'label' name=ID 'for' multi?='each'? expression=XExpression ('unless'
		//	unlessCondition=XExpression)?;
		@Override public ParserRule getRule() { return rule; }
		
		//^hidden?='hidden'? 'label' name=ID 'for' multi?='each'? expression=XExpression ('unless' unlessCondition=XExpression)?
		public Group getGroup() { return cGroup; }
		
		//^hidden?='hidden'?
		public Assignment getHiddenAssignment_0() { return cHiddenAssignment_0; }
		
		//'hidden'
		public Keyword getHiddenHiddenKeyword_0_0() { return cHiddenHiddenKeyword_0_0; }
		
		//'label'
		public Keyword getLabelKeyword_1() { return cLabelKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'for'
		public Keyword getForKeyword_3() { return cForKeyword_3; }
		
		//multi?='each'?
		public Assignment getMultiAssignment_4() { return cMultiAssignment_4; }
		
		//'each'
		public Keyword getMultiEachKeyword_4_0() { return cMultiEachKeyword_4_0; }
		
		//expression=XExpression
		public Assignment getExpressionAssignment_5() { return cExpressionAssignment_5; }
		
		//XExpression
		public RuleCall getExpressionXExpressionParserRuleCall_5_0() { return cExpressionXExpressionParserRuleCall_5_0; }
		
		//('unless' unlessCondition=XExpression)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'unless'
		public Keyword getUnlessKeyword_6_0() { return cUnlessKeyword_6_0; }
		
		//unlessCondition=XExpression
		public Assignment getUnlessConditionAssignment_6_1() { return cUnlessConditionAssignment_6_1; }
		
		//XExpression
		public RuleCall getUnlessConditionXExpressionParserRuleCall_6_1_0() { return cUnlessConditionXExpressionParserRuleCall_6_1_0; }
	}
	public class EdgeMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.xtext.graphview.map.GraphViewMapping.EdgeMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cHiddenAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cHiddenHiddenKeyword_0_0 = (Keyword)cHiddenAssignment_0.eContents().get(0);
		private final Keyword cEdgeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cForKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMultiAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cMultiEachKeyword_4_0 = (Keyword)cMultiAssignment_4.eContents().get(0);
		private final Assignment cExpressionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cExpressionXExpressionParserRuleCall_5_0 = (RuleCall)cExpressionAssignment_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cSourceMappingAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cSourceMappingEdgeEndMappingParserRuleCall_7_0 = (RuleCall)cSourceMappingAssignment_7.eContents().get(0);
		private final Keyword cEqualsSignGreaterThanSignKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cTargetMappingAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cTargetMappingEdgeEndMappingParserRuleCall_9_0 = (RuleCall)cTargetMappingAssignment_9.eContents().get(0);
		private final Assignment cMappingsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cMappingsLabelMappingParserRuleCall_10_0 = (RuleCall)cMappingsAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cUnlessKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cUnlessConditionAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cUnlessConditionXExpressionParserRuleCall_12_1_0 = (RuleCall)cUnlessConditionAssignment_12_1.eContents().get(0);
		
		//EdgeMapping:
		//	^hidden?='hidden'? 'edge' name=ID 'for' multi?='each'? expression=XExpression '{'
		//	sourceMapping=EdgeEndMapping?
		//	'=>'
		//	targetMapping=EdgeEndMapping?
		//	mappings+=LabelMapping*
		//	'}' ('unless' unlessCondition=XExpression)?;
		@Override public ParserRule getRule() { return rule; }
		
		//^hidden?='hidden'? 'edge' name=ID 'for' multi?='each'? expression=XExpression '{' sourceMapping=EdgeEndMapping? '=>'
		//targetMapping=EdgeEndMapping? mappings+=LabelMapping* '}' ('unless' unlessCondition=XExpression)?
		public Group getGroup() { return cGroup; }
		
		//^hidden?='hidden'?
		public Assignment getHiddenAssignment_0() { return cHiddenAssignment_0; }
		
		//'hidden'
		public Keyword getHiddenHiddenKeyword_0_0() { return cHiddenHiddenKeyword_0_0; }
		
		//'edge'
		public Keyword getEdgeKeyword_1() { return cEdgeKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'for'
		public Keyword getForKeyword_3() { return cForKeyword_3; }
		
		//multi?='each'?
		public Assignment getMultiAssignment_4() { return cMultiAssignment_4; }
		
		//'each'
		public Keyword getMultiEachKeyword_4_0() { return cMultiEachKeyword_4_0; }
		
		//expression=XExpression
		public Assignment getExpressionAssignment_5() { return cExpressionAssignment_5; }
		
		//XExpression
		public RuleCall getExpressionXExpressionParserRuleCall_5_0() { return cExpressionXExpressionParserRuleCall_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//sourceMapping=EdgeEndMapping?
		public Assignment getSourceMappingAssignment_7() { return cSourceMappingAssignment_7; }
		
		//EdgeEndMapping
		public RuleCall getSourceMappingEdgeEndMappingParserRuleCall_7_0() { return cSourceMappingEdgeEndMappingParserRuleCall_7_0; }
		
		//'=>'
		public Keyword getEqualsSignGreaterThanSignKeyword_8() { return cEqualsSignGreaterThanSignKeyword_8; }
		
		//targetMapping=EdgeEndMapping?
		public Assignment getTargetMappingAssignment_9() { return cTargetMappingAssignment_9; }
		
		//EdgeEndMapping
		public RuleCall getTargetMappingEdgeEndMappingParserRuleCall_9_0() { return cTargetMappingEdgeEndMappingParserRuleCall_9_0; }
		
		//mappings+=LabelMapping*
		public Assignment getMappingsAssignment_10() { return cMappingsAssignment_10; }
		
		//LabelMapping
		public RuleCall getMappingsLabelMappingParserRuleCall_10_0() { return cMappingsLabelMappingParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//('unless' unlessCondition=XExpression)?
		public Group getGroup_12() { return cGroup_12; }
		
		//'unless'
		public Keyword getUnlessKeyword_12_0() { return cUnlessKeyword_12_0; }
		
		//unlessCondition=XExpression
		public Assignment getUnlessConditionAssignment_12_1() { return cUnlessConditionAssignment_12_1; }
		
		//XExpression
		public RuleCall getUnlessConditionXExpressionParserRuleCall_12_1_0() { return cUnlessConditionXExpressionParserRuleCall_12_1_0; }
	}
	public class EdgeEndMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.xtext.graphview.map.GraphViewMapping.EdgeEndMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cRefKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Assignment cCallAssignment_0_1 = (Assignment)cAlternatives_0.eContents().get(1);
		private final Keyword cCallCallKeyword_0_1_0 = (Keyword)cCallAssignment_0_1.eContents().get(0);
		private final Assignment cReferencedMappingAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cReferencedMappingAbstractMappingDefinitionCrossReference_1_0 = (CrossReference)cReferencedMappingAssignment_1.eContents().get(0);
		private final RuleCall cReferencedMappingAbstractMappingDefinitionIDTerminalRuleCall_1_0_1 = (RuleCall)cReferencedMappingAbstractMappingDefinitionCrossReference_1_0.eContents().get(1);
		private final Keyword cForKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionXExpressionParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		
		//EdgeEndMapping:
		//	('ref' | call?='call') referencedMapping=[AbstractMappingDefinition] 'for' expression=XExpression;
		@Override public ParserRule getRule() { return rule; }
		
		//('ref' | call?='call') referencedMapping=[AbstractMappingDefinition] 'for' expression=XExpression
		public Group getGroup() { return cGroup; }
		
		//('ref' | call?='call')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'ref'
		public Keyword getRefKeyword_0_0() { return cRefKeyword_0_0; }
		
		//call?='call'
		public Assignment getCallAssignment_0_1() { return cCallAssignment_0_1; }
		
		//'call'
		public Keyword getCallCallKeyword_0_1_0() { return cCallCallKeyword_0_1_0; }
		
		//referencedMapping=[AbstractMappingDefinition]
		public Assignment getReferencedMappingAssignment_1() { return cReferencedMappingAssignment_1; }
		
		//[AbstractMappingDefinition]
		public CrossReference getReferencedMappingAbstractMappingDefinitionCrossReference_1_0() { return cReferencedMappingAbstractMappingDefinitionCrossReference_1_0; }
		
		//ID
		public RuleCall getReferencedMappingAbstractMappingDefinitionIDTerminalRuleCall_1_0_1() { return cReferencedMappingAbstractMappingDefinitionIDTerminalRuleCall_1_0_1; }
		
		//'for'
		public Keyword getForKeyword_2() { return cForKeyword_2; }
		
		//expression=XExpression
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }
		
		//XExpression
		public RuleCall getExpressionXExpressionParserRuleCall_3_0() { return cExpressionXExpressionParserRuleCall_3_0; }
	}
	public class MappingCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.xtext.graphview.map.GraphViewMapping.MappingCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Assignment cHiddenAssignment_0_0_0 = (Assignment)cGroup_0_0.eContents().get(0);
		private final Keyword cHiddenHiddenKeyword_0_0_0_0 = (Keyword)cHiddenAssignment_0_0_0.eContents().get(0);
		private final Assignment cCallAssignment_0_0_1 = (Assignment)cGroup_0_0.eContents().get(1);
		private final Keyword cCallCallKeyword_0_0_1_0 = (Keyword)cCallAssignment_0_0_1.eContents().get(0);
		private final Keyword cOpenKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cReferencedMappingAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cReferencedMappingAbstractMappingDefinitionCrossReference_1_0 = (CrossReference)cReferencedMappingAssignment_1.eContents().get(0);
		private final RuleCall cReferencedMappingAbstractMappingDefinitionIDTerminalRuleCall_1_0_1 = (RuleCall)cReferencedMappingAbstractMappingDefinitionCrossReference_1_0.eContents().get(1);
		private final Keyword cForKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMultiAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cMultiEachKeyword_3_0 = (Keyword)cMultiAssignment_3.eContents().get(0);
		private final Assignment cExpressionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExpressionXExpressionParserRuleCall_4_0 = (RuleCall)cExpressionAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cUnlessKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cUnlessConditionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cUnlessConditionXExpressionParserRuleCall_5_1_0 = (RuleCall)cUnlessConditionAssignment_5_1.eContents().get(0);
		
		//MappingCall:
		//	(^hidden?='hidden'? call?='call' | 'open') referencedMapping=[AbstractMappingDefinition] 'for' multi?='each'?
		//	expression=XExpression ('unless' unlessCondition=XExpression)?;
		@Override public ParserRule getRule() { return rule; }
		
		//(^hidden?='hidden'? call?='call' | 'open') referencedMapping=[AbstractMappingDefinition] 'for' multi?='each'?
		//expression=XExpression ('unless' unlessCondition=XExpression)?
		public Group getGroup() { return cGroup; }
		
		//(^hidden?='hidden'? call?='call' | 'open')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//^hidden?='hidden'? call?='call'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//^hidden?='hidden'?
		public Assignment getHiddenAssignment_0_0_0() { return cHiddenAssignment_0_0_0; }
		
		//'hidden'
		public Keyword getHiddenHiddenKeyword_0_0_0_0() { return cHiddenHiddenKeyword_0_0_0_0; }
		
		//call?='call'
		public Assignment getCallAssignment_0_0_1() { return cCallAssignment_0_0_1; }
		
		//'call'
		public Keyword getCallCallKeyword_0_0_1_0() { return cCallCallKeyword_0_0_1_0; }
		
		//'open'
		public Keyword getOpenKeyword_0_1() { return cOpenKeyword_0_1; }
		
		//referencedMapping=[AbstractMappingDefinition]
		public Assignment getReferencedMappingAssignment_1() { return cReferencedMappingAssignment_1; }
		
		//[AbstractMappingDefinition]
		public CrossReference getReferencedMappingAbstractMappingDefinitionCrossReference_1_0() { return cReferencedMappingAbstractMappingDefinitionCrossReference_1_0; }
		
		//ID
		public RuleCall getReferencedMappingAbstractMappingDefinitionIDTerminalRuleCall_1_0_1() { return cReferencedMappingAbstractMappingDefinitionIDTerminalRuleCall_1_0_1; }
		
		//'for'
		public Keyword getForKeyword_2() { return cForKeyword_2; }
		
		//multi?='each'?
		public Assignment getMultiAssignment_3() { return cMultiAssignment_3; }
		
		//'each'
		public Keyword getMultiEachKeyword_3_0() { return cMultiEachKeyword_3_0; }
		
		//expression=XExpression
		public Assignment getExpressionAssignment_4() { return cExpressionAssignment_4; }
		
		//XExpression
		public RuleCall getExpressionXExpressionParserRuleCall_4_0() { return cExpressionXExpressionParserRuleCall_4_0; }
		
		//('unless' unlessCondition=XExpression)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'unless'
		public Keyword getUnlessKeyword_5_0() { return cUnlessKeyword_5_0; }
		
		//unlessCondition=XExpression
		public Assignment getUnlessConditionAssignment_5_1() { return cUnlessConditionAssignment_5_1; }
		
		//XExpression
		public RuleCall getUnlessConditionXExpressionParserRuleCall_5_1_0() { return cUnlessConditionXExpressionParserRuleCall_5_1_0; }
	}
	
	
	private final DiagramMappingElements pDiagramMapping;
	private final AbstractExpressionMappingElements pAbstractExpressionMapping;
	private final NodeMappingElements pNodeMapping;
	private final LabelMappingElements pLabelMapping;
	private final EdgeMappingElements pEdgeMapping;
	private final EdgeEndMappingElements pEdgeEndMapping;
	private final MappingCallElements pMappingCall;
	
	private final Grammar grammar;
	
	private final XbaseGrammarAccess gaXbase;
	
	private final XtypeGrammarAccess gaXtype;

	@Inject
	public GraphViewMappingGrammarAccess(GrammarProvider grammarProvider,
			XbaseGrammarAccess gaXbase,
			XtypeGrammarAccess gaXtype) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaXbase = gaXbase;
		this.gaXtype = gaXtype;
		this.pDiagramMapping = new DiagramMappingElements();
		this.pAbstractExpressionMapping = new AbstractExpressionMappingElements();
		this.pNodeMapping = new NodeMappingElements();
		this.pLabelMapping = new LabelMappingElements();
		this.pEdgeMapping = new EdgeMappingElements();
		this.pEdgeEndMapping = new EdgeEndMappingElements();
		this.pMappingCall = new MappingCallElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.eclipse.xtext.graphview.map.GraphViewMapping".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public XbaseGrammarAccess getXbaseGrammarAccess() {
		return gaXbase;
	}
	
	public XtypeGrammarAccess getXtypeGrammarAccess() {
		return gaXtype;
	}

	
	//DiagramMapping:
	//	importSection=XImportSection?
	//	'diagram' name=QualifiedName 'type' typeGuard=JvmTypeReference '{'
	//	mappings+=AbstractExpressionMapping*
	//	'}' ('unless' unlessCondition=XExpression)?;
	public DiagramMappingElements getDiagramMappingAccess() {
		return pDiagramMapping;
	}
	
	public ParserRule getDiagramMappingRule() {
		return getDiagramMappingAccess().getRule();
	}
	
	//AbstractExpressionMapping:
	//	NodeMapping | LabelMapping | EdgeMapping | MappingCall;
	public AbstractExpressionMappingElements getAbstractExpressionMappingAccess() {
		return pAbstractExpressionMapping;
	}
	
	public ParserRule getAbstractExpressionMappingRule() {
		return getAbstractExpressionMappingAccess().getRule();
	}
	
	//NodeMapping:
	//	^hidden?='hidden'? 'node' name=ID 'for' multi?='each'? expression=XExpression '{'
	//	mappings+=AbstractExpressionMapping*
	//	'}' ('unless' unlessCondition=XExpression)?;
	public NodeMappingElements getNodeMappingAccess() {
		return pNodeMapping;
	}
	
	public ParserRule getNodeMappingRule() {
		return getNodeMappingAccess().getRule();
	}
	
	//LabelMapping:
	//	^hidden?='hidden'? 'label' name=ID 'for' multi?='each'? expression=XExpression ('unless'
	//	unlessCondition=XExpression)?;
	public LabelMappingElements getLabelMappingAccess() {
		return pLabelMapping;
	}
	
	public ParserRule getLabelMappingRule() {
		return getLabelMappingAccess().getRule();
	}
	
	//EdgeMapping:
	//	^hidden?='hidden'? 'edge' name=ID 'for' multi?='each'? expression=XExpression '{'
	//	sourceMapping=EdgeEndMapping?
	//	'=>'
	//	targetMapping=EdgeEndMapping?
	//	mappings+=LabelMapping*
	//	'}' ('unless' unlessCondition=XExpression)?;
	public EdgeMappingElements getEdgeMappingAccess() {
		return pEdgeMapping;
	}
	
	public ParserRule getEdgeMappingRule() {
		return getEdgeMappingAccess().getRule();
	}
	
	//EdgeEndMapping:
	//	('ref' | call?='call') referencedMapping=[AbstractMappingDefinition] 'for' expression=XExpression;
	public EdgeEndMappingElements getEdgeEndMappingAccess() {
		return pEdgeEndMapping;
	}
	
	public ParserRule getEdgeEndMappingRule() {
		return getEdgeEndMappingAccess().getRule();
	}
	
	//MappingCall:
	//	(^hidden?='hidden'? call?='call' | 'open') referencedMapping=[AbstractMappingDefinition] 'for' multi?='each'?
	//	expression=XExpression ('unless' unlessCondition=XExpression)?;
	public MappingCallElements getMappingCallAccess() {
		return pMappingCall;
	}
	
	public ParserRule getMappingCallRule() {
		return getMappingCallAccess().getRule();
	}
	
	//XExpression:
	//	XAssignment;
	public XbaseGrammarAccess.XExpressionElements getXExpressionAccess() {
		return gaXbase.getXExpressionAccess();
	}
	
	public ParserRule getXExpressionRule() {
		return getXExpressionAccess().getRule();
	}
	
	//XAssignment XExpression:
	//	{XAssignment} feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign value=XAssignment | XOrExpression
	//	(=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMultiAssign])
	//	rightOperand=XAssignment)?;
	public XbaseGrammarAccess.XAssignmentElements getXAssignmentAccess() {
		return gaXbase.getXAssignmentAccess();
	}
	
	public ParserRule getXAssignmentRule() {
		return getXAssignmentAccess().getRule();
	}
	
	//OpSingleAssign:
	//	'=';
	public XbaseGrammarAccess.OpSingleAssignElements getOpSingleAssignAccess() {
		return gaXbase.getOpSingleAssignAccess();
	}
	
	public ParserRule getOpSingleAssignRule() {
		return getOpSingleAssignAccess().getRule();
	}
	
	//OpMultiAssign:
	//	'+=' | '-=' | '*=' | '/=' | '%=' |
	//	'<' '<' '=' |
	//	'>' '>'? '>=';
	public XbaseGrammarAccess.OpMultiAssignElements getOpMultiAssignAccess() {
		return gaXbase.getOpMultiAssignAccess();
	}
	
	public ParserRule getOpMultiAssignRule() {
		return getOpMultiAssignAccess().getRule();
	}
	
	//XOrExpression XExpression:
	//	XAndExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOr])
	//	rightOperand=XAndExpression)*;
	public XbaseGrammarAccess.XOrExpressionElements getXOrExpressionAccess() {
		return gaXbase.getXOrExpressionAccess();
	}
	
	public ParserRule getXOrExpressionRule() {
		return getXOrExpressionAccess().getRule();
	}
	
	//OpOr:
	//	'||';
	public XbaseGrammarAccess.OpOrElements getOpOrAccess() {
		return gaXbase.getOpOrAccess();
	}
	
	public ParserRule getOpOrRule() {
		return getOpOrAccess().getRule();
	}
	
	//XAndExpression XExpression:
	//	XEqualityExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAnd])
	//	rightOperand=XEqualityExpression)*;
	public XbaseGrammarAccess.XAndExpressionElements getXAndExpressionAccess() {
		return gaXbase.getXAndExpressionAccess();
	}
	
	public ParserRule getXAndExpressionRule() {
		return getXAndExpressionAccess().getRule();
	}
	
	//OpAnd:
	//	'&&';
	public XbaseGrammarAccess.OpAndElements getOpAndAccess() {
		return gaXbase.getOpAndAccess();
	}
	
	public ParserRule getOpAndRule() {
		return getOpAndAccess().getRule();
	}
	
	//XEqualityExpression XExpression:
	//	XRelationalExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpEquality])
	//	rightOperand=XRelationalExpression)*;
	public XbaseGrammarAccess.XEqualityExpressionElements getXEqualityExpressionAccess() {
		return gaXbase.getXEqualityExpressionAccess();
	}
	
	public ParserRule getXEqualityExpressionRule() {
		return getXEqualityExpressionAccess().getRule();
	}
	
	//OpEquality:
	//	'==' | '!=' | '===' | '!==';
	public XbaseGrammarAccess.OpEqualityElements getOpEqualityAccess() {
		return gaXbase.getOpEqualityAccess();
	}
	
	public ParserRule getOpEqualityRule() {
		return getOpEqualityAccess().getRule();
	}
	
	//XRelationalExpression XExpression:
	//	XOtherOperatorExpression (=> ({XInstanceOfExpression.expression=current} 'instanceof') type=JvmTypeReference |
	//	=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpCompare])
	//	rightOperand=XOtherOperatorExpression)*;
	public XbaseGrammarAccess.XRelationalExpressionElements getXRelationalExpressionAccess() {
		return gaXbase.getXRelationalExpressionAccess();
	}
	
	public ParserRule getXRelationalExpressionRule() {
		return getXRelationalExpressionAccess().getRule();
	}
	
	//OpCompare:
	//	'>=' | '<' '=' | '>' | '<';
	public XbaseGrammarAccess.OpCompareElements getOpCompareAccess() {
		return gaXbase.getOpCompareAccess();
	}
	
	public ParserRule getOpCompareRule() {
		return getOpCompareAccess().getRule();
	}
	
	//XOtherOperatorExpression XExpression:
	//	XAdditiveExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOther])
	//	rightOperand=XAdditiveExpression)*;
	public XbaseGrammarAccess.XOtherOperatorExpressionElements getXOtherOperatorExpressionAccess() {
		return gaXbase.getXOtherOperatorExpressionAccess();
	}
	
	public ParserRule getXOtherOperatorExpressionRule() {
		return getXOtherOperatorExpressionAccess().getRule();
	}
	
	//OpOther:
	//	'->'
	//	| '..<'
	//	| '>' '..'
	//	| '..'
	//	| '=>'
	//	| '>' (=> ('>' '>') | '>') | '<' (=> ('<' '<') | '<' | '=>') | '<>'
	//	| '?:';
	public XbaseGrammarAccess.OpOtherElements getOpOtherAccess() {
		return gaXbase.getOpOtherAccess();
	}
	
	public ParserRule getOpOtherRule() {
		return getOpOtherAccess().getRule();
	}
	
	//XAdditiveExpression XExpression:
	//	XMultiplicativeExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAdd])
	//	rightOperand=XMultiplicativeExpression)*;
	public XbaseGrammarAccess.XAdditiveExpressionElements getXAdditiveExpressionAccess() {
		return gaXbase.getXAdditiveExpressionAccess();
	}
	
	public ParserRule getXAdditiveExpressionRule() {
		return getXAdditiveExpressionAccess().getRule();
	}
	
	//OpAdd:
	//	'+' | '-';
	public XbaseGrammarAccess.OpAddElements getOpAddAccess() {
		return gaXbase.getOpAddAccess();
	}
	
	public ParserRule getOpAddRule() {
		return getOpAddAccess().getRule();
	}
	
	//XMultiplicativeExpression XExpression:
	//	XUnaryOperation (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMulti])
	//	rightOperand=XUnaryOperation)*;
	public XbaseGrammarAccess.XMultiplicativeExpressionElements getXMultiplicativeExpressionAccess() {
		return gaXbase.getXMultiplicativeExpressionAccess();
	}
	
	public ParserRule getXMultiplicativeExpressionRule() {
		return getXMultiplicativeExpressionAccess().getRule();
	}
	
	//OpMulti:
	//	'*' | '**' | '/' | '%';
	public XbaseGrammarAccess.OpMultiElements getOpMultiAccess() {
		return gaXbase.getOpMultiAccess();
	}
	
	public ParserRule getOpMultiRule() {
		return getOpMultiAccess().getRule();
	}
	
	//XUnaryOperation XExpression:
	//	{XUnaryOperation} feature=[types::JvmIdentifiableElement|OpUnary] operand=XUnaryOperation
	//	| XCastedExpression;
	public XbaseGrammarAccess.XUnaryOperationElements getXUnaryOperationAccess() {
		return gaXbase.getXUnaryOperationAccess();
	}
	
	public ParserRule getXUnaryOperationRule() {
		return getXUnaryOperationAccess().getRule();
	}
	
	//OpUnary:
	//	"!" | "-" | "+";
	public XbaseGrammarAccess.OpUnaryElements getOpUnaryAccess() {
		return gaXbase.getOpUnaryAccess();
	}
	
	public ParserRule getOpUnaryRule() {
		return getOpUnaryAccess().getRule();
	}
	
	//XCastedExpression XExpression:
	//	XPostfixOperation (=> ({XCastedExpression.target=current} 'as') type=JvmTypeReference)*;
	public XbaseGrammarAccess.XCastedExpressionElements getXCastedExpressionAccess() {
		return gaXbase.getXCastedExpressionAccess();
	}
	
	public ParserRule getXCastedExpressionRule() {
		return getXCastedExpressionAccess().getRule();
	}
	
	//XPostfixOperation XExpression:
	//	XMemberFeatureCall => ({XPostfixOperation.operand=current} feature=[types::JvmIdentifiableElement|OpPostfix])?;
	public XbaseGrammarAccess.XPostfixOperationElements getXPostfixOperationAccess() {
		return gaXbase.getXPostfixOperationAccess();
	}
	
	public ParserRule getXPostfixOperationRule() {
		return getXPostfixOperationAccess().getRule();
	}
	
	//OpPostfix:
	//	"++" | "--";
	public XbaseGrammarAccess.OpPostfixElements getOpPostfixAccess() {
		return gaXbase.getOpPostfixAccess();
	}
	
	public ParserRule getOpPostfixRule() {
		return getOpPostfixAccess().getRule();
	}
	
	//XMemberFeatureCall XExpression:
	//	XPrimaryExpression (=> ({XAssignment.assignable=current} ('.' | explicitStatic?="::")
	//	feature=[types::JvmIdentifiableElement|FeatureCallID] OpSingleAssign) value=XAssignment
	//	| => ({XMemberFeatureCall.memberCallTarget=current} ("." | nullSafe?="?." | explicitStatic?="::")) ('<'
	//	typeArguments+=JvmArgumentTypeReference (',' typeArguments+=JvmArgumentTypeReference)* '>')?
	//	feature=[types::JvmIdentifiableElement|IdOrSuper] (=> explicitOperationCall?='(' (memberCallArguments+=XShortClosure
	//	| memberCallArguments+=XExpression (',' memberCallArguments+=XExpression)*)?
	//	')')?
	//	memberCallArguments+=XClosure?)*;
	public XbaseGrammarAccess.XMemberFeatureCallElements getXMemberFeatureCallAccess() {
		return gaXbase.getXMemberFeatureCallAccess();
	}
	
	public ParserRule getXMemberFeatureCallRule() {
		return getXMemberFeatureCallAccess().getRule();
	}
	
	//XPrimaryExpression XExpression:
	//	XConstructorCall | XBlockExpression | XSwitchExpression | XSynchronizedExpression | XFeatureCall | XLiteral |
	//	XIfExpression | XForLoopExpression | XBasicForLoopExpression | XWhileExpression | XDoWhileExpression |
	//	XThrowExpression | XReturnExpression | XTryCatchFinallyExpression | XParenthesizedExpression;
	public XbaseGrammarAccess.XPrimaryExpressionElements getXPrimaryExpressionAccess() {
		return gaXbase.getXPrimaryExpressionAccess();
	}
	
	public ParserRule getXPrimaryExpressionRule() {
		return getXPrimaryExpressionAccess().getRule();
	}
	
	//XLiteral XExpression:
	//	XCollectionLiteral | XClosure | XBooleanLiteral | XNumberLiteral | XNullLiteral | XStringLiteral | XTypeLiteral;
	public XbaseGrammarAccess.XLiteralElements getXLiteralAccess() {
		return gaXbase.getXLiteralAccess();
	}
	
	public ParserRule getXLiteralRule() {
		return getXLiteralAccess().getRule();
	}
	
	//XCollectionLiteral:
	//	XSetLiteral | XListLiteral;
	public XbaseGrammarAccess.XCollectionLiteralElements getXCollectionLiteralAccess() {
		return gaXbase.getXCollectionLiteralAccess();
	}
	
	public ParserRule getXCollectionLiteralRule() {
		return getXCollectionLiteralAccess().getRule();
	}
	
	//XSetLiteral:
	//	{XSetLiteral} '#' '{' (elements+=XExpression (',' elements+=XExpression)*)? '}';
	public XbaseGrammarAccess.XSetLiteralElements getXSetLiteralAccess() {
		return gaXbase.getXSetLiteralAccess();
	}
	
	public ParserRule getXSetLiteralRule() {
		return getXSetLiteralAccess().getRule();
	}
	
	//XListLiteral:
	//	{XListLiteral} '#' '[' (elements+=XExpression (',' elements+=XExpression)*)? ']';
	public XbaseGrammarAccess.XListLiteralElements getXListLiteralAccess() {
		return gaXbase.getXListLiteralAccess();
	}
	
	public ParserRule getXListLiteralRule() {
		return getXListLiteralAccess().getRule();
	}
	
	//XClosure XExpression:
	//	=> ({XClosure}
	//	'[')
	//	=> ((declaredFormalParameters+=JvmFormalParameter (',' declaredFormalParameters+=JvmFormalParameter)*)?
	//	explicitSyntax?='|')?
	//	expression=XExpressionInClosure
	//	']';
	public XbaseGrammarAccess.XClosureElements getXClosureAccess() {
		return gaXbase.getXClosureAccess();
	}
	
	public ParserRule getXClosureRule() {
		return getXClosureAccess().getRule();
	}
	
	//XExpressionInClosure XExpression:
	//	{XBlockExpression} (expressions+=XExpressionOrVarDeclaration ';'?)*;
	public XbaseGrammarAccess.XExpressionInClosureElements getXExpressionInClosureAccess() {
		return gaXbase.getXExpressionInClosureAccess();
	}
	
	public ParserRule getXExpressionInClosureRule() {
		return getXExpressionInClosureAccess().getRule();
	}
	
	//XShortClosure XExpression:
	//	=> ({XClosure} (declaredFormalParameters+=JvmFormalParameter (',' declaredFormalParameters+=JvmFormalParameter)*)?
	//	explicitSyntax?='|') expression=XExpression;
	public XbaseGrammarAccess.XShortClosureElements getXShortClosureAccess() {
		return gaXbase.getXShortClosureAccess();
	}
	
	public ParserRule getXShortClosureRule() {
		return getXShortClosureAccess().getRule();
	}
	
	//XParenthesizedExpression XExpression:
	//	'(' XExpression ')';
	public XbaseGrammarAccess.XParenthesizedExpressionElements getXParenthesizedExpressionAccess() {
		return gaXbase.getXParenthesizedExpressionAccess();
	}
	
	public ParserRule getXParenthesizedExpressionRule() {
		return getXParenthesizedExpressionAccess().getRule();
	}
	
	//XIfExpression XExpression:
	//	{XIfExpression}
	//	'if' '(' if=XExpression ')'
	//	then=XExpression (=> 'else' else=XExpression)?;
	public XbaseGrammarAccess.XIfExpressionElements getXIfExpressionAccess() {
		return gaXbase.getXIfExpressionAccess();
	}
	
	public ParserRule getXIfExpressionRule() {
		return getXIfExpressionAccess().getRule();
	}
	
	//XSwitchExpression XExpression:
	//	{XSwitchExpression}
	//	'switch' (=> ('(' declaredParam=JvmFormalParameter ':') switch=XExpression ')'
	//	| => (declaredParam=JvmFormalParameter ':')? switch=XExpression) '{'
	//	cases+=XCasePart* ('default' ':' default=XExpression)?
	//	'}';
	public XbaseGrammarAccess.XSwitchExpressionElements getXSwitchExpressionAccess() {
		return gaXbase.getXSwitchExpressionAccess();
	}
	
	public ParserRule getXSwitchExpressionRule() {
		return getXSwitchExpressionAccess().getRule();
	}
	
	//XCasePart:
	//	{XCasePart} typeGuard=JvmTypeReference? ('case' case=XExpression)? (':' then=XExpression | fallThrough?=',');
	public XbaseGrammarAccess.XCasePartElements getXCasePartAccess() {
		return gaXbase.getXCasePartAccess();
	}
	
	public ParserRule getXCasePartRule() {
		return getXCasePartAccess().getRule();
	}
	
	//XForLoopExpression XExpression:
	//	=> ({XForLoopExpression}
	//	'for' '(' declaredParam=JvmFormalParameter ':') forExpression=XExpression ')'
	//	eachExpression=XExpression;
	public XbaseGrammarAccess.XForLoopExpressionElements getXForLoopExpressionAccess() {
		return gaXbase.getXForLoopExpressionAccess();
	}
	
	public ParserRule getXForLoopExpressionRule() {
		return getXForLoopExpressionAccess().getRule();
	}
	
	//XBasicForLoopExpression XExpression:
	//	{XBasicForLoopExpression}
	//	'for' '(' (initExpressions+=XExpressionOrVarDeclaration (',' initExpressions+=XExpressionOrVarDeclaration)*)? ';'
	//	expression=XExpression? ';' (updateExpressions+=XExpression (',' updateExpressions+=XExpression)*)? ')'
	//	eachExpression=XExpression;
	public XbaseGrammarAccess.XBasicForLoopExpressionElements getXBasicForLoopExpressionAccess() {
		return gaXbase.getXBasicForLoopExpressionAccess();
	}
	
	public ParserRule getXBasicForLoopExpressionRule() {
		return getXBasicForLoopExpressionAccess().getRule();
	}
	
	//XWhileExpression XExpression:
	//	{XWhileExpression}
	//	'while' '(' predicate=XExpression ')'
	//	body=XExpression;
	public XbaseGrammarAccess.XWhileExpressionElements getXWhileExpressionAccess() {
		return gaXbase.getXWhileExpressionAccess();
	}
	
	public ParserRule getXWhileExpressionRule() {
		return getXWhileExpressionAccess().getRule();
	}
	
	//XDoWhileExpression XExpression:
	//	{XDoWhileExpression}
	//	'do'
	//	body=XExpression
	//	'while' '(' predicate=XExpression ')';
	public XbaseGrammarAccess.XDoWhileExpressionElements getXDoWhileExpressionAccess() {
		return gaXbase.getXDoWhileExpressionAccess();
	}
	
	public ParserRule getXDoWhileExpressionRule() {
		return getXDoWhileExpressionAccess().getRule();
	}
	
	//XBlockExpression XExpression:
	//	{XBlockExpression}
	//	'{' (expressions+=XExpressionOrVarDeclaration ';'?)*
	//	'}';
	public XbaseGrammarAccess.XBlockExpressionElements getXBlockExpressionAccess() {
		return gaXbase.getXBlockExpressionAccess();
	}
	
	public ParserRule getXBlockExpressionRule() {
		return getXBlockExpressionAccess().getRule();
	}
	
	//XExpressionOrVarDeclaration XExpression:
	//	XVariableDeclaration | XExpression;
	public XbaseGrammarAccess.XExpressionOrVarDeclarationElements getXExpressionOrVarDeclarationAccess() {
		return gaXbase.getXExpressionOrVarDeclarationAccess();
	}
	
	public ParserRule getXExpressionOrVarDeclarationRule() {
		return getXExpressionOrVarDeclarationAccess().getRule();
	}
	
	//XVariableDeclaration XExpression:
	//	{XVariableDeclaration} (writeable?='var' | 'val') (=> (type=JvmTypeReference name=ValidID) | name=ValidID) ('='
	//	right=XExpression)?;
	public XbaseGrammarAccess.XVariableDeclarationElements getXVariableDeclarationAccess() {
		return gaXbase.getXVariableDeclarationAccess();
	}
	
	public ParserRule getXVariableDeclarationRule() {
		return getXVariableDeclarationAccess().getRule();
	}
	
	//JvmFormalParameter types::JvmFormalParameter:
	//	parameterType=JvmTypeReference? name=ValidID;
	public XbaseGrammarAccess.JvmFormalParameterElements getJvmFormalParameterAccess() {
		return gaXbase.getJvmFormalParameterAccess();
	}
	
	public ParserRule getJvmFormalParameterRule() {
		return getJvmFormalParameterAccess().getRule();
	}
	
	//FullJvmFormalParameter types::JvmFormalParameter:
	//	parameterType=JvmTypeReference name=ValidID;
	public XbaseGrammarAccess.FullJvmFormalParameterElements getFullJvmFormalParameterAccess() {
		return gaXbase.getFullJvmFormalParameterAccess();
	}
	
	public ParserRule getFullJvmFormalParameterRule() {
		return getFullJvmFormalParameterAccess().getRule();
	}
	
	//XFeatureCall XExpression:
	//	{XFeatureCall} ('<' typeArguments+=JvmArgumentTypeReference (',' typeArguments+=JvmArgumentTypeReference)* '>')?
	//	feature=[types::JvmIdentifiableElement|IdOrSuper] (=> explicitOperationCall?='(' (featureCallArguments+=XShortClosure
	//	| featureCallArguments+=XExpression (',' featureCallArguments+=XExpression)*)?
	//	')')?
	//	featureCallArguments+=XClosure?;
	public XbaseGrammarAccess.XFeatureCallElements getXFeatureCallAccess() {
		return gaXbase.getXFeatureCallAccess();
	}
	
	public ParserRule getXFeatureCallRule() {
		return getXFeatureCallAccess().getRule();
	}
	
	//FeatureCallID:
	//	ValidID | 'extends' | 'static' | 'import' | 'extension';
	public XbaseGrammarAccess.FeatureCallIDElements getFeatureCallIDAccess() {
		return gaXbase.getFeatureCallIDAccess();
	}
	
	public ParserRule getFeatureCallIDRule() {
		return getFeatureCallIDAccess().getRule();
	}
	
	//IdOrSuper:
	//	FeatureCallID | 'super';
	public XbaseGrammarAccess.IdOrSuperElements getIdOrSuperAccess() {
		return gaXbase.getIdOrSuperAccess();
	}
	
	public ParserRule getIdOrSuperRule() {
		return getIdOrSuperAccess().getRule();
	}
	
	//XConstructorCall XExpression:
	//	{XConstructorCall}
	//	'new' constructor=[types::JvmConstructor|QualifiedName] (=> '<' typeArguments+=JvmArgumentTypeReference (','
	//	typeArguments+=JvmArgumentTypeReference)* '>')? (=> explicitConstructorCall?='(' (arguments+=XShortClosure
	//	| arguments+=XExpression (',' arguments+=XExpression)*)?
	//	')')?
	//	arguments+=XClosure?;
	public XbaseGrammarAccess.XConstructorCallElements getXConstructorCallAccess() {
		return gaXbase.getXConstructorCallAccess();
	}
	
	public ParserRule getXConstructorCallRule() {
		return getXConstructorCallAccess().getRule();
	}
	
	//XBooleanLiteral XExpression:
	//	{XBooleanLiteral} ('false' | isTrue?='true');
	public XbaseGrammarAccess.XBooleanLiteralElements getXBooleanLiteralAccess() {
		return gaXbase.getXBooleanLiteralAccess();
	}
	
	public ParserRule getXBooleanLiteralRule() {
		return getXBooleanLiteralAccess().getRule();
	}
	
	//XNullLiteral XExpression:
	//	{XNullLiteral} 'null';
	public XbaseGrammarAccess.XNullLiteralElements getXNullLiteralAccess() {
		return gaXbase.getXNullLiteralAccess();
	}
	
	public ParserRule getXNullLiteralRule() {
		return getXNullLiteralAccess().getRule();
	}
	
	//XNumberLiteral XExpression:
	//	{XNumberLiteral} value=Number;
	public XbaseGrammarAccess.XNumberLiteralElements getXNumberLiteralAccess() {
		return gaXbase.getXNumberLiteralAccess();
	}
	
	public ParserRule getXNumberLiteralRule() {
		return getXNumberLiteralAccess().getRule();
	}
	
	//XStringLiteral XExpression:
	//	{XStringLiteral} value=STRING;
	public XbaseGrammarAccess.XStringLiteralElements getXStringLiteralAccess() {
		return gaXbase.getXStringLiteralAccess();
	}
	
	public ParserRule getXStringLiteralRule() {
		return getXStringLiteralAccess().getRule();
	}
	
	//XTypeLiteral XExpression:
	//	{XTypeLiteral} 'typeof' '(' type=[types::JvmType|QualifiedName] arrayDimensions+=ArrayBrackets* ')';
	public XbaseGrammarAccess.XTypeLiteralElements getXTypeLiteralAccess() {
		return gaXbase.getXTypeLiteralAccess();
	}
	
	public ParserRule getXTypeLiteralRule() {
		return getXTypeLiteralAccess().getRule();
	}
	
	//XThrowExpression XExpression:
	//	{XThrowExpression} 'throw' expression=XExpression;
	public XbaseGrammarAccess.XThrowExpressionElements getXThrowExpressionAccess() {
		return gaXbase.getXThrowExpressionAccess();
	}
	
	public ParserRule getXThrowExpressionRule() {
		return getXThrowExpressionAccess().getRule();
	}
	
	//XReturnExpression XExpression:
	//	{XReturnExpression} 'return' -> expression=XExpression?;
	public XbaseGrammarAccess.XReturnExpressionElements getXReturnExpressionAccess() {
		return gaXbase.getXReturnExpressionAccess();
	}
	
	public ParserRule getXReturnExpressionRule() {
		return getXReturnExpressionAccess().getRule();
	}
	
	//XTryCatchFinallyExpression XExpression:
	//	{XTryCatchFinallyExpression}
	//	'try'
	//	expression=XExpression (catchClauses+=XCatchClause+ (=> 'finally' finallyExpression=XExpression)?
	//	| 'finally' finallyExpression=XExpression);
	public XbaseGrammarAccess.XTryCatchFinallyExpressionElements getXTryCatchFinallyExpressionAccess() {
		return gaXbase.getXTryCatchFinallyExpressionAccess();
	}
	
	public ParserRule getXTryCatchFinallyExpressionRule() {
		return getXTryCatchFinallyExpressionAccess().getRule();
	}
	
	//XSynchronizedExpression XExpression:
	//	=> ({XSynchronizedExpression}
	//	'synchronized' '(') param=XExpression ')' expression=XExpression;
	public XbaseGrammarAccess.XSynchronizedExpressionElements getXSynchronizedExpressionAccess() {
		return gaXbase.getXSynchronizedExpressionAccess();
	}
	
	public ParserRule getXSynchronizedExpressionRule() {
		return getXSynchronizedExpressionAccess().getRule();
	}
	
	//XCatchClause:
	//	=> 'catch' '(' declaredParam=FullJvmFormalParameter ')' expression=XExpression;
	public XbaseGrammarAccess.XCatchClauseElements getXCatchClauseAccess() {
		return gaXbase.getXCatchClauseAccess();
	}
	
	public ParserRule getXCatchClauseRule() {
		return getXCatchClauseAccess().getRule();
	}
	
	//@Override
	//QualifiedName:
	//	ValidID (=> '.' ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaXbase.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//Number hidden():
	//	HEX | (INT | DECIMAL) ('.' (INT | DECIMAL))?;
	public XbaseGrammarAccess.NumberElements getNumberAccess() {
		return gaXbase.getNumberAccess();
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}
	
	///**
	// * Dummy rule, for "better" downwards compatibility, since GrammarAccess generates non-static inner classes,
	// * which makes downstream grammars break on classloading, when a rule is removed.
	// */ StaticQualifier:
	//	(ValidID '::')+;
	public XbaseGrammarAccess.StaticQualifierElements getStaticQualifierAccess() {
		return gaXbase.getStaticQualifierAccess();
	}
	
	public ParserRule getStaticQualifierRule() {
		return getStaticQualifierAccess().getRule();
	}
	
	//terminal HEX:
	//	('0x' | '0X') ('0'..'9' | 'a'..'f' | 'A'..'F' | '_')+ ('#' (('b' | 'B') ('i' | 'I') | ('l' | 'L')))?;
	public TerminalRule getHEXRule() {
		return gaXbase.getHEXRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9' ('0'..'9' | '_')*;
	public TerminalRule getINTRule() {
		return gaXbase.getINTRule();
	}
	
	//terminal DECIMAL:
	//	INT (('e' | 'E') ('+' | '-')? INT)? (('b' | 'B') ('i' | 'I' | 'd' | 'D') | ('l' | 'L' | 'd' | 'D' | 'f' | 'F'))?;
	public TerminalRule getDECIMALRule() {
		return gaXbase.getDECIMALRule();
	}
	
	//JvmTypeReference:
	//	JvmParameterizedTypeReference => ({JvmGenericArrayTypeReference.componentType=current} ArrayBrackets)*
	//	| XFunctionTypeRef;
	public XtypeGrammarAccess.JvmTypeReferenceElements getJvmTypeReferenceAccess() {
		return gaXtype.getJvmTypeReferenceAccess();
	}
	
	public ParserRule getJvmTypeReferenceRule() {
		return getJvmTypeReferenceAccess().getRule();
	}
	
	//ArrayBrackets:
	//	'[' ']';
	public XtypeGrammarAccess.ArrayBracketsElements getArrayBracketsAccess() {
		return gaXtype.getArrayBracketsAccess();
	}
	
	public ParserRule getArrayBracketsRule() {
		return getArrayBracketsAccess().getRule();
	}
	
	//XFunctionTypeRef:
	//	('(' (paramTypes+=JvmTypeReference (',' paramTypes+=JvmTypeReference)*)? ')')? '=>' returnType=JvmTypeReference;
	public XtypeGrammarAccess.XFunctionTypeRefElements getXFunctionTypeRefAccess() {
		return gaXtype.getXFunctionTypeRefAccess();
	}
	
	public ParserRule getXFunctionTypeRefRule() {
		return getXFunctionTypeRefAccess().getRule();
	}
	
	//JvmParameterizedTypeReference:
	//	type=[JvmType|super::QualifiedName] (=> '<' arguments+=JvmArgumentTypeReference (','
	//	arguments+=JvmArgumentTypeReference)* '>' (=> ({JvmInnerTypeReference.outer=current} '.') type=[JvmType|ValidID] (=>
	//	'<' arguments+=JvmArgumentTypeReference (',' arguments+=JvmArgumentTypeReference)* '>')?)*)?;
	public XtypeGrammarAccess.JvmParameterizedTypeReferenceElements getJvmParameterizedTypeReferenceAccess() {
		return gaXtype.getJvmParameterizedTypeReferenceAccess();
	}
	
	public ParserRule getJvmParameterizedTypeReferenceRule() {
		return getJvmParameterizedTypeReferenceAccess().getRule();
	}
	
	//JvmArgumentTypeReference JvmTypeReference:
	//	JvmTypeReference | JvmWildcardTypeReference;
	public XtypeGrammarAccess.JvmArgumentTypeReferenceElements getJvmArgumentTypeReferenceAccess() {
		return gaXtype.getJvmArgumentTypeReferenceAccess();
	}
	
	public ParserRule getJvmArgumentTypeReferenceRule() {
		return getJvmArgumentTypeReferenceAccess().getRule();
	}
	
	//JvmWildcardTypeReference:
	//	{JvmWildcardTypeReference} '?' (constraints+=JvmUpperBound constraints+=JvmUpperBoundAnded*
	//	| constraints+=JvmLowerBound constraints+=JvmLowerBoundAnded*)?;
	public XtypeGrammarAccess.JvmWildcardTypeReferenceElements getJvmWildcardTypeReferenceAccess() {
		return gaXtype.getJvmWildcardTypeReferenceAccess();
	}
	
	public ParserRule getJvmWildcardTypeReferenceRule() {
		return getJvmWildcardTypeReferenceAccess().getRule();
	}
	
	//JvmUpperBound:
	//	'extends' typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundElements getJvmUpperBoundAccess() {
		return gaXtype.getJvmUpperBoundAccess();
	}
	
	public ParserRule getJvmUpperBoundRule() {
		return getJvmUpperBoundAccess().getRule();
	}
	
	//JvmUpperBoundAnded JvmUpperBound:
	//	'&' typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundAndedElements getJvmUpperBoundAndedAccess() {
		return gaXtype.getJvmUpperBoundAndedAccess();
	}
	
	public ParserRule getJvmUpperBoundAndedRule() {
		return getJvmUpperBoundAndedAccess().getRule();
	}
	
	//JvmLowerBound:
	//	'super' typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmLowerBoundElements getJvmLowerBoundAccess() {
		return gaXtype.getJvmLowerBoundAccess();
	}
	
	public ParserRule getJvmLowerBoundRule() {
		return getJvmLowerBoundAccess().getRule();
	}
	
	//JvmLowerBoundAnded JvmLowerBound:
	//	'&' typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmLowerBoundAndedElements getJvmLowerBoundAndedAccess() {
		return gaXtype.getJvmLowerBoundAndedAccess();
	}
	
	public ParserRule getJvmLowerBoundAndedRule() {
		return getJvmLowerBoundAndedAccess().getRule();
	}
	
	//JvmTypeParameter:
	//	name=ValidID (constraints+=JvmUpperBound constraints+=JvmUpperBoundAnded*)?;
	public XtypeGrammarAccess.JvmTypeParameterElements getJvmTypeParameterAccess() {
		return gaXtype.getJvmTypeParameterAccess();
	}
	
	public ParserRule getJvmTypeParameterRule() {
		return getJvmTypeParameterAccess().getRule();
	}
	
	//QualifiedNameWithWildcard:
	//	super::QualifiedName '.' '*';
	public XtypeGrammarAccess.QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return gaXtype.getQualifiedNameWithWildcardAccess();
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}
	
	//ValidID:
	//	ID;
	public XtypeGrammarAccess.ValidIDElements getValidIDAccess() {
		return gaXtype.getValidIDAccess();
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}
	
	//XImportSection:
	//	importDeclarations+=XImportDeclaration+;
	public XtypeGrammarAccess.XImportSectionElements getXImportSectionAccess() {
		return gaXtype.getXImportSectionAccess();
	}
	
	public ParserRule getXImportSectionRule() {
		return getXImportSectionAccess().getRule();
	}
	
	//XImportDeclaration:
	//	'import' (static?='static' extension?='extension'? importedType=[JvmDeclaredType|QualifiedNameInStaticImport]
	//	(wildcard?='*' | memberName=ValidID) | importedType=[JvmDeclaredType|super::QualifiedName] |
	//	importedNamespace=QualifiedNameWithWildcard) ';'?;
	public XtypeGrammarAccess.XImportDeclarationElements getXImportDeclarationAccess() {
		return gaXtype.getXImportDeclarationAccess();
	}
	
	public ParserRule getXImportDeclarationRule() {
		return getXImportDeclarationAccess().getRule();
	}
	
	//QualifiedNameInStaticImport:
	//	(ValidID '.')+;
	public XtypeGrammarAccess.QualifiedNameInStaticImportElements getQualifiedNameInStaticImportAccess() {
		return gaXtype.getQualifiedNameInStaticImportAccess();
	}
	
	public ParserRule getQualifiedNameInStaticImportRule() {
		return getQualifiedNameInStaticImportAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '$' | '_') ('a'..'z' | 'A'..'Z' | '$' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaXtype.getIDRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"'? |
	//	"'" ('\\' . | !('\\' | "'"))* "'"?;
	public TerminalRule getSTRINGRule() {
		return gaXtype.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaXtype.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaXtype.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaXtype.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaXtype.getANY_OTHERRule();
	}
}
