/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.style


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GraphViewStyleRuntimeModule extends AbstractGraphViewStyleRuntimeModule {
}
