/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.map.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class GraphViewMappingEditor extends XbaseEditor {
}
