/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.style.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class GraphViewStyleUiModule extends AbstractGraphViewStyleUiModule {
}
