/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.style.ide


/**
 * Use this class to register ide components.
 */
class GraphViewStyleIdeModule extends AbstractGraphViewStyleIdeModule {
}
