/**
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.style.ide;

import org.eclipse.xtext.graphview.style.ide.AbstractGraphViewStyleIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GraphViewStyleIdeModule extends AbstractGraphViewStyleIdeModule {
}
