/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.style.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.graphview.style.parser.antlr.internal.InternalGraphViewStyleParser;
import org.eclipse.xtext.graphview.style.services.GraphViewStyleGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GraphViewStyleParser extends AbstractAntlrParser {

	@Inject
	private GraphViewStyleGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGraphViewStyleParser createParser(XtextTokenStream stream) {
		return new InternalGraphViewStyleParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "StyleSheet";
	}

	public GraphViewStyleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GraphViewStyleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
