/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.map.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.graphview.map.ui.internal.MapActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GraphViewMappingUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MapActivator.getInstance().getInjector("org.eclipse.xtext.graphview.map.GraphViewMapping");
	}

}
