/*
 * generated by Xtext
 */
package org.eclipse.xtext.graphview.map;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GraphViewMappingRuntimeModule extends org.eclipse.xtext.graphview.map.AbstractGraphViewMappingRuntimeModule {

}
