/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.map.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractGraphViewMappingScopeProvider extends XbaseBatchScopeProvider {
}
