/*
 * generated by Xtext 2.13.0
 */
package org.eclipse.xtext.graphview.map.ide


/**
 * Use this class to register ide components.
 */
class GraphViewMappingIdeModule extends AbstractGraphViewMappingIdeModule {
}
