/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.xtext.graphview.style.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.graphview.style.ui.internal.StyleActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GraphViewStyleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(StyleActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		StyleActivator activator = StyleActivator.getInstance();
		return activator != null ? activator.getInjector(StyleActivator.ORG_ECLIPSE_XTEXT_GRAPHVIEW_STYLE_GRAPHVIEWSTYLE) : null;
	}

}
